project:
  type: website
  output-dir: docs
  resources:
    - data/
    - logos/

website:
  title: "ASA DataFest<sup><small>TM</small></sup>"
  search: false
  navbar:
    pinned: true
    background: "#00539B" # match logo
    left:
      - text: "Home"
        href: "/index.html"
      - text: "Sign Up"
        href: "#signup"
      - text: "Schedule"
        href: "schedule.html"
      - text: "About"
        menu:
          - text: "Overview"
            href: "about.html"
          - text: "Code of Conduct"
            href: "coc.html"
      - text: "FAQ"
        href: "#faq"
      - text: "Resources"
        href: "resources.html"
      - text: "Sponsors"
        href: "sponsors.html"
      - text: "Winners"
        href: "winners.html"
 
format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    page-layout: full
    include-after-body: aria-fix.html



