baseurl = "/"
languageCode = "en-us"
defaultContentLanguage = "en-us"
title = "STA 210"
theme = "material"
#disqusShortname = ""
# googleAnalytics = ""
paginate = 7
relativeURLs = true
uglyURLs = true
publishDir = "docs"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
  post = "/:year/:month/:slug/"

[taxonomies]
  tag = "tags"
  category = "categories"
  archive = "archives"

[author]
  name = "Dr. Maria Tackett"
  bio = ""
  job = "Assistant Professor of the Practice"
  location = "Duke University"
  gravatarEmail = "maria.tackett@duke.edu"
  # Your profile picture
#  picture = ""
  twitter = "MT_statistics"
 
# Menu Configuration
[[menu.main]]
  weight = 1
  identifier = "home"
  name = "Home"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-home\"></i>"
  url = "/"
  
[[menu.main]]
  weight = 2
  identifier = "schedule"
  name = "schedule"
  pre = "<i class=\"material-icons\">calendar_today</i>"
  url = "/schedule.html"
  
[[menu.main]]
  weight = 3
  identifier = "signup"
  name = "Sign Up"
  pre = "<i class='fa fa-check fa-lg'></i>"
  url = "/signup.html"
  
  
[[menu.main]]
  weight = 4
  identifier = "workshops"
  name = "Workshops"
  pre = "<i class='fa fa-check fa-lg'></i>"
  url = "/workshops.html"



  
[[menu.footer]]
  weight = 1
  identifier = "Duke"
  name = "Duke StatSci"
  pre = "<i class=\"button-icon fa fa fa-map-marker\"></i>"
  url = "http://stat.duke.edu/"
[[menu.footer]]
  weight = 2
  name = "ASA DataFest"
  pre = "<i class=\"button-icon fa fa fa-chart-bar\"></i>"
  url = "https://ww2.amstat.org/education/datafest/"
[[menu.footer]]
  weight = 3
  identifier = "twitter"
  name = "Twitter"
  pre = "<i class=\"button-icon fa fa fa-twitter\"></i>"
  url = "https://twitter.com/dukedatafest"
[[menu.footer]]

[params]
  dateFormat = "January 2, 2006"
  background = "https://www2.stat.duke.edu/courses/Spring20/sta210.001/img/bikeshare-reg-plots.png"
  favicon = "https://www2.stat.duke.edu/courses/Spring20/sta210.001/img/sta210_sticker_small.png"
