---
title: "Schedule"
---

**Friday, March 24**

- 5:00pm: Early check-in option available at Perkins Link near the Help Desk (floor L1)
- 6:00pm: Data kick-off at Levine Science Research Center (LSRC) B101.
- 6:30pm: Welcome and meet the data!
- 7:00pm: Perkins Link and Dinner - Check-in at Perkins Link near the Help Desk (floor L1)
- 9:00pm: DataFest support and consulting runs until 9pm.

**Saturday, March 25**

- 10:00am: open + breakfast + coffee + tea
- 12:30pm: Group photo
- 1:00pm: Lunch
- 2:00pm: Activity break
- 4:00pm: Activity break
- 6:00pm: Dinner & trivia
- 9:00pm: DataFest support and consulting runs until 9pm.

**Sunday, March 26**

*Consultants available for help until 12:00pm.*

- 10:00am: open + breakfast + coffee + tea
- 12:30pm: Lunch + projects due!
- 1:00pm-2:30pm: Round 1 judging
- 3:00pm-5:00pm: Final round of judging & awards in Levine Science Research Center (LSRC) B101

#### Google map addresses

- Perkins library: [411 Chapel Drive
Durham, NC 27708](https://goo.gl/maps/JGGawKRZBm2ygq4S8)
- Levine Science Research Center (LSRC): [308 Research Dr, Durham, NC 27710](https://goo.gl/maps/ERowZZSPJwrp3i1MA)