---
title: "Sponsorship"
---

ASA DataFest<small><sup>TM</sup></small> at Duke cannot run without your support!

Please see below for Sponsorship opportunities. Note that your donations are tax-deductible.

Please [contact us](mailto:alexander.fisher@duke.edu) if you are interested in sponsorship and/or have any questions.

### Impact of Your Sponsorship

Your sponsorship of ASA DataFest<small><sup>TM</sup></small> benefits the ASA DataFest<small><sup>TM</sup></small> @ Duke. Any residual funds will support undergraduate statistics education, foster the new generation of data science, and advance our mission of promoting the use of data in the understanding of our environment, our social relationships, and our physical and virtual selves.

### Benefits of Sponsorship

Sponsors will be provided with various advertising and recruiting opportunities. But equally important is your time! Please consider visiting us as a "VIP Consultant". Drop by for a couple of hours and talk to the teams to point them in the right direction. It's a wonderful recruiting opportunity and lots of fun, too. We ask that visitors sign up for a time slot so that we'll know when to expect you, but we won't hold you to it.

### Sponsorship Levels

#### Cauchy Sponsor - $5000 and above

- Nomination of a judge for the final round of presentations
- If requested, company/organization information session on Duke campus advertised to Duke StatSci students as well as all 2023 ASA DataFest<small><sup>TM</sup></small> participants (we will provide the space and advertise your event)
- All benefits of Pareto Sponsor


#### Pareto Sponsor - $2,500 - $4,999

- Table for HR/recruitment for four hours during DataFest
- All benefits of Lognormal Sponsor


#### Lognormal Sponsor - $1,000 - $2,499

- Access to resume book of ASA DataFestTM participants
- All benefits of Weibull Sponsors


#### Weibull Sponsor -  <$1000

- Logo and link on ASA DataFest<small><sup>TM</sup></small> website
- Company/organization name on food table display

### Ways to give

#### Online

You can make your donation online at https://www.gifts.duke.edu. Please enter the amount you would like to give, and click "Choose an Area", then "Still can’t find your designation of choice?" In the text field asking which area of Duke you'd like to support, type "*DataFest: 3991698*". After clicking "Next", choose "One Time Gift" on the following page. Complete the remaining prompts for your information and payment details.

#### By mail

You can also mail your donation to the following address:
  
  Alumni and Development Records  
  Duke University, Box 90581  
  Durham, NC 27708-0581  
  
Please make your check payable to Duke University, and note *"Department of Statistical Science - DataFest, Fund code: 3991698"* on your check. If you need to contact the Alumni and Development Records office directly, you can do so at (919) 684-2338. 

More information can be found on the [Duke Forward](https://giving.duke.edu/) page.

### Sponsorship questions?

Please do not hesitate to contact [Alexander Fisher](mailto:alexander.fisher@duke.edu), ASA DataFest<small><sup>TM</sup></small> @ Duke coordinator, with any questions.