---
title: "Winners"
---

# 2024 Winners

### Best Statistical Analysis

[Discrepancies in Chapter Difficulty and Outcome](/presentations/Team283Boys.pdf) by Eddy Ding, Daniel Henderson, Maxim Chadaev and Siddhant Borkar.

*The judges were impressed by the creation of a statistic to evaluate the relative difficulty of chapters and subsequent recommendations to the data provider.*

### Best Insight

[Plagiarism on CourseKata](/presentations/TeamTomato.pdf) by Evan Glas, Henry Holbrook, Ben Perry, Addison Phelps and Roy Chen.

*The judges were impressed by the unique topic analyzed and story told by this team regarding plagiarism in the online platform.*
 

### Best Visualizations

[From "Hello World" to Beyond](/presentations/TeamJeltJian.pdf) by Eric Rios, Lisa Wang, Luopeiwen Yi and Jiayi Zhou.

*The judges were impressed by this team's ability to create clear, easy to understand visuals of how students spend their time.*


### Best Use of Outside Data

[Chapter Engagement](/presentations/TeamTKGA.pdf) by Anmol Sapru, Tate Staples, Gabriel Paley and Kevin Lee.

*The judges were impressed by this team's ability to scrape data from the platform's web page such as number of pixels as a measure of "scroll length" to determine a relationship between chapter length and chapter engagement.*

<!-- [**Recruitment, distribution and questions**](/presentations/NEON-presentation.pdf) by Sophie Guo, Carrie Hang, Hanoc Codjie, Lipsa Tripathy & Alejandra Camargo. -->

<!-- *The judges were impressed by formal vs. informal language analysis grounded in literature.* -->

### Judges' Pick

*Project recognized by the judges for outstanding achievement outside of the core award categories.*

[Learning Style Segmentation for Personalized Education](/presentations/TeamJLAndTheJets.pdf) by Alex Katopodis, Miles King, Jonathan Levitan and Jackson Peurach.

*The judges were impressed by this group's identification of nuanced user segments and the detailed recommendations to the data providers.* 

### Honorable Mentions

[Student Clusters](/presentations/TeamDataMIDS.pdf) by Gunel Aghakishiyeva, Daniela Jimenez and Shaila Guereca.
 
[Beyond the Numbers: Unlocking Student Engagement in Statistics](/presentations/Team08.pdf) by Senam Adedze, Sonia Zhu, Wangley Soares Martins, Mia Lam and Sam Reid.



# Past winners

[Click here](/past-winners.html) to see past winners.